// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Setu.Api.Data;

#nullable disable

namespace Setu.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317000001_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: This is a simplified snapshot after adding performance indexes.
            // The actual model structure remains the same, only indexes are added.
            // For the complete model definition, refer to ApplicationDbContextModelSnapshot.cs
            
            // Companies indexes added
            modelBuilder.Entity("Setu.Api.Models.Company", b =>
            {
                b.HasIndex("UserId")
                    .HasDatabaseName("IX_Companies_UserId");
            });

            // Products indexes added
            modelBuilder.Entity("Setu.Api.Models.Product", b =>
            {
                b.HasIndex("CompanyId")
                    .HasDatabaseName("IX_Products_CompanyId");
                
                b.HasIndex("UserId")
                    .HasDatabaseName("IX_Products_UserId");
                
                b.HasIndex("CompanyId", "UserId")
                    .HasDatabaseName("IX_Products_CompanyId_UserId");
            });

            // Customers indexes added
            modelBuilder.Entity("Setu.Api.Models.Customer", b =>
            {
                b.HasIndex("CompanyId")
                    .HasDatabaseName("IX_Customers_CompanyId");
                
                b.HasIndex("UserId")
                    .HasDatabaseName("IX_Customers_UserId");
            });

            // Transactions indexes added
            modelBuilder.Entity("Setu.Api.Models.Transaction", b =>
            {
                b.HasIndex("CompanyId")
                    .HasDatabaseName("IX_Transactions_CompanyId");
                
                b.HasIndex("UserId")
                    .HasDatabaseName("IX_Transactions_UserId");
                
                b.HasIndex("CompanyId", "Date")
                    .HasDatabaseName("IX_Transactions_CompanyId_Date");
            });

            // TransactionItems indexes added
            modelBuilder.Entity("Setu.Api.Models.TransactionItem", b =>
            {
                b.HasIndex("ProductId")
                    .HasDatabaseName("IX_TransactionItems_ProductId");
                
                b.HasIndex("TransactionId")
                    .HasDatabaseName("IX_TransactionItems_TransactionId");
            });
#pragma warning restore 612, 618
        }
    }
}
